using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonthlyExpenseTracker.Migrations
{
    /// <inheritdoc />
    public partial class ChangeCategoryIdToGuid : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                TRUNCATE TABLE "Transactions", "Categories";

                ALTER TABLE "Transactions"
                    DROP CONSTRAINT "FK_Transactions_Categories_CategoryId";

                ALTER TABLE "Categories"
                    ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;

                ALTER TABLE "Transactions"
                    ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;

                ALTER TABLE "Categories"
                    ALTER COLUMN "Id" TYPE uuid USING NULL::uuid;

                ALTER TABLE "Transactions"
                    ALTER COLUMN "Id" TYPE uuid USING NULL::uuid;

                ALTER TABLE "Transactions"
                    ALTER COLUMN "CategoryId" TYPE uuid USING NULL::uuid;

                ALTER TABLE "Transactions"
                    ADD CONSTRAINT "FK_Transactions_Categories_CategoryId"
                    FOREIGN KEY ("CategoryId")
                    REFERENCES "Categories" ("Id")
                    ON DELETE RESTRICT;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                TRUNCATE TABLE "Transactions", "Categories";

                ALTER TABLE "Transactions"
                    DROP CONSTRAINT "FK_Transactions_Categories_CategoryId";

                ALTER TABLE "Transactions"
                    ALTER COLUMN "CategoryId" TYPE integer USING NULL::integer;

                ALTER TABLE "Transactions"
                    ALTER COLUMN "Id" TYPE integer USING NULL::integer;

                ALTER TABLE "Categories"
                    ALTER COLUMN "Id" TYPE integer USING NULL::integer;

                ALTER TABLE "Categories"
                    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

                ALTER TABLE "Transactions"
                    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

                ALTER TABLE "Transactions"
                    ADD CONSTRAINT "FK_Transactions_Categories_CategoryId"
                    FOREIGN KEY ("CategoryId")
                    REFERENCES "Categories" ("Id")
                    ON DELETE RESTRICT;
                """);
        }
    }
}
